services:
  - type: web
    name: issue-tracker
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeployOnPush: true
    
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: PORT
        value: 3000
      - key: DATABASE_URL          
        fromDatabase:
          name: issue-tracker-db
          property: connectionString
      - key: RAILS_MASTER_KEY      
        sync: false           

databases:
  - name: issue-tracker-db
    databaseName: issue_tracker
    user: rails
    plan: free
